version: '3.7'

services:
  database:
    image: postgres
    container_name: setup
    restart: always
    ports:
      - 5442:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=setup_docker
      - POSTGRES_DB=setup_docker
    volumes:
      - pgdata:/data/postgres


volumes:
  pgdata:
    driver: local