version: '3.8'

services:
  # web:
  #   build:
  #     context: ../freitas-gas-web
  #     dockerfile: Dockerfile
  #   image: web:v1
  #   ports:
  #     - "3000:3000"
  #   env_file:
  #     - ../freitas-gas-web/.env.production
  #   networks:
  #     - freitas-network
  # backend:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   image: backend:v1
  #   ports:
  #     - "5000:5000"
  #   env_file:
  #     - .env
  #   networks:
  #     - freitas-network
  database:
    image: postgres:15
    container_name: freitas
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./data/pg:/var/lib/postgresql/data
    networks:
      - freitas-network

  redis:
    container_name: freitas-redis
    image: redis:alpine
    ports:
      - 6379:6379
    networks:
      - freitas-network

volumes:
  pgadmin_data:
    driver: local
  pgdata:
    driver: local

networks:
  freitas-network:
    driver: bridge