version: '3.7'

services:
  database:
    image: postgres
    container_name: setup
    restart: always
    ports:
      - 5442:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=setup_docker
      - POSTGRES_DB=setup_docker
    volumes:
      - ./data/pg:/var/lib/postgresql/data
  redis:
    container_name: setup-redis
    image: redis:alpine
    ports:
      - 6379:6379
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  pgadmin_data:
    driver: local
  pgdata:
    driver: local