version: '3.8'

services:
  database:
    image: postgres:15
    container_name: freitas
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=freitas_docker
      - POSTGRES_DB=basic
    volumes:
      - ./data/pg:/var/lib/postgresql/data

  redis:
    container_name: freitas-redis
    image: redis:alpine
    ports:
      - 6379:6379
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  pgadmin_data:
    driver: local
  pgdata:
    driver: local

networks:
  freitas-network:
    driver: bridge