name: End-to-End Tests

on:
  push:
    branches:
      - main

jobs:
  e2e_tests:
    name: Run End-to-End Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: test_database
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: yarn install

    - name: Run E2E tests
      env:
        DATABASE_URL: postgres://test_user:test_password@localhost:5432/test_database
      run: yarn test:e2e
